# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    # entrypointを指定すると、devcontainerでもcommandが実行されてしまう。
    # entrypoint: /myapp/entrypoint.sh
    command: bash -c "rm tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      # - ".:/myapp"
      - "myapp:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development

volumes:
  myapp:
  postgres_data:
